version: "3.8"

services:
  scan-main-service:
    container_name: scan-main-service
    image: scan-main-service:latest
    build:
      context: ./main-service
      dockerfile: dockerfile
    command: npm run start-dev
    volumes:
      - ./main-service/src:/app/src
      - scan-main-service-node-modules:/app/node_modules
    ports:
      - 4000:4000
    networks:
      - scanner-net
  event-bus-scan-service:
    container_name: event-bus-scan-service
    image: event-bus-scan-service:latest
    build:
      context: ./event-bus
      dockerfile: dockerfile
    command: npm run start-dev
    volumes:
      - ./event-bus/src:/app/src
      - event-bus-scan-service-node-modules:/app/node_modules
    ports:
      - 4010:4010
    networks:
      - scanner-net 
  scan-service:
    container_name: scan-service
    image: scan-service:latest
    build:
      context: ./scan-service
      dockerfile: dockerfile
    command: npm run start-dev
    volumes:
      - ./scan-service/src:/app/src
      - scan-service-node-modules:/app/node_modules
    ports:
      - 4001:4001
    networks:
      - scanner-net 
   
  scan-main-service-db:
    container_name: scan-main-service-db
    image: postgres:12.4
    restart: always
    networks:
      - scanner-net
    environment: 
      POSTGRES_PASSWORD: LugLSdU6kaHEHp7m
      POSTGRES_USER: scan_api_user
      POSTGRES_DB: scan_api
    ports:
      - 5450:5432
    volumes:
      - scan-main-service-db-data:/var/lib/postgresql/data
  event-bus-service-db:
    container_name: event-bus-service-db
    image: postgres:12.4
    restart: always
    networks:
      - scanner-net
    environment: 
      POSTGRES_PASSWORD: KZajde4FhVM6T7ZG
      POSTGRES_USER: scan_api_user
      POSTGRES_DB: scan_api
    ports:
      - 5460:5432
    volumes:
      - event-bus-service-db-data:/var/lib/postgresql/data
  scan-service-db:
    container_name: scan-service-db
    image: postgres:12.4
    restart: always
    networks:
      - scanner-net
    environment: 
      POSTGRES_PASSWORD: H38RHQWR8ZKx6uua
      POSTGRES_USER: scan_api_user
      POSTGRES_DB: scan_api
    ports:
      - 5460:5432
    volumes:
      - scan-service-db-data:/var/lib/postgresql/data
    
volumes:
  scan-service-db-data:
  event-bus-service-db-data:
  scan-main-service-db-data:
  scan-main-service-node-modules:
  event-bus-scan-service-node-modules:
  scan-service-node-modules:

networks:
  scanner-net: 
     driver: bridge
