CREATE TABLE IF NOT EXISTS finding (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  data JSONB,
  created_by VARCHAR,
  updated_by VARCHAR,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
